<?php
//// 

$countries = array("Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo", "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia (Hrvatska)", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "France Metropolitan", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard and Mc Donald Islands", "Holy See (Vatican City State)", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran (Islamic Republic of)", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan", "Lao, People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia, The Former Yugoslav Republic of", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of", "Monaco", "Mongolia", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Seychelles", "Sierra Leone", "Singapore", "Slovakia (Slovak Republic)", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "St. Helena", "St. Pierre and Miquelon", "Sudan", "Suriname", "Svalbard and Jan Mayen Islands", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic", "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Virgin Islands (British)", "Virgin Islands (U.S.)", "Wallis and Futuna Islands", "Yemen", "Yugoslavia", "Zambia", "Zimbabwe");

//// 

$country_array = array(
"AF" => "Afghanistan",
"AL" => "Albania",
"DZ" => "Algeria",
"AS" => "American Samoa",
"AD" => "Andorra",
"AO" => "Angola",
"AI" => "Anguilla",
"AQ" => "Antarctica",
"AG" => "Antigua and Barbuda",
"AR" => "Argentina",
"AM" => "Armenia",
"AW" => "Aruba",
"AU" => "Australia",
"AT" => "Austria",
"AZ" => "Azerbaijan",
"BS" => "Bahamas",
"BH" => "Bahrain",
"BD" => "Bangladesh",
"BB" => "Barbados",
"BY" => "Belarus",
"BE" => "Belgium",
"BZ" => "Belize",
"BJ" => "Benin",
"BM" => "Bermuda",
"BT" => "Bhutan",
"BO" => "Bolivia",
"BA" => "Bosnia and Herzegovina",
"BW" => "Botswana",
"BV" => "Bouvet Island",
"BR" => "Brazil",
"BQ" => "British Antarctic Territory",
"IO" => "British Indian Ocean Territory",
"VG" => "British Virgin Islands",
"BN" => "Brunei",
"BG" => "Bulgaria",
"BF" => "Burkina Faso",
"BI" => "Burundi",
"KH" => "Cambodia",
"CM" => "Cameroon",
"CA" => "Canada",
"CT" => "Canton and Enderbury Islands",
"CV" => "Cape Verde",
"KY" => "Cayman Islands",
"CF" => "Central African Republic",
"TD" => "Chad",
"CL" => "Chile",
"CN" => "China",
"CX" => "Christmas Island",
"CC" => "Cocos [Keeling] Islands",
"CO" => "Colombia",
"KM" => "Comoros",
"CG" => "Congo - Brazzaville",
"CD" => "Congo - Kinshasa",
"CK" => "Cook Islands",
"CR" => "Costa Rica",
"HR" => "Croatia",
"CU" => "Cuba",
"CY" => "Cyprus",
"CZ" => "Czech Republic",
"CI" => "Côte d’Ivoire",
"DK" => "Denmark",
"DJ" => "Djibouti",
"DM" => "Dominica",
"DO" => "Dominican Republic",
"NQ" => "Dronning Maud Land",
"DD" => "East Germany",
"EC" => "Ecuador",
"EG" => "Egypt",
"SV" => "El Salvador",
"GQ" => "Equatorial Guinea",
"ER" => "Eritrea",
"EE" => "Estonia",
"ET" => "Ethiopia",
"FK" => "Falkland Islands",
"FO" => "Faroe Islands",
"FJ" => "Fiji",
"FI" => "Finland",
"FR" => "France",
"GF" => "French Guiana",
"PF" => "French Polynesia",
"TF" => "French Southern Territories",
"FQ" => "French Southern and Antarctic Territories",
"GA" => "Gabon",
"GM" => "Gambia",
"GE" => "Georgia",
"DE" => "Germany",
"GH" => "Ghana",
"GI" => "Gibraltar",
"GR" => "Greece",
"GL" => "Greenland",
"GD" => "Grenada",
"GP" => "Guadeloupe",
"GU" => "Guam",
"GT" => "Guatemala",
"GG" => "Guernsey",
"GN" => "Guinea",
"GW" => "Guinea-Bissau",
"GY" => "Guyana",
"HT" => "Haiti",
"HM" => "Heard Island and McDonald Islands",
"HN" => "Honduras",
"HK" => "Hong Kong SAR China",
"HU" => "Hungary",
"IS" => "Iceland",
"IN" => "India",
"ID" => "Indonesia",
"IR" => "Iran",
"IQ" => "Iraq",
"IE" => "Ireland",
"IM" => "Isle of Man",
"IL" => "Israel",
"IT" => "Italy",
"JM" => "Jamaica",
"JP" => "Japan",
"JE" => "Jersey",
"JT" => "Johnston Island",
"JO" => "Jordan",
"KZ" => "Kazakhstan",
"KE" => "Kenya",
"KI" => "Kiribati",
"KW" => "Kuwait",
"KG" => "Kyrgyzstan",
"LA" => "Laos",
"LV" => "Latvia",
"LB" => "Lebanon",
"LS" => "Lesotho",
"LR" => "Liberia",
"LY" => "Libya",
"LI" => "Liechtenstein",
"LT" => "Lithuania",
"LU" => "Luxembourg",
"MO" => "Macau SAR China",
"MK" => "Macedonia",
"MG" => "Madagascar",
"MW" => "Malawi",
"MY" => "Malaysia",
"MV" => "Maldives",
"ML" => "Mali",
"MT" => "Malta",
"MH" => "Marshall Islands",
"MQ" => "Martinique",
"MR" => "Mauritania",
"MU" => "Mauritius",
"YT" => "Mayotte",
"FX" => "Metropolitan France",
"MX" => "Mexico",
"FM" => "Micronesia",
"MI" => "Midway Islands",
"MD" => "Moldova",
"MC" => "Monaco",
"MN" => "Mongolia",
"ME" => "Montenegro",
"MS" => "Montserrat",
"MA" => "Morocco",
"MZ" => "Mozambique",
"MM" => "Myanmar [Burma]",
"NA" => "Namibia",
"NR" => "Nauru",
"NP" => "Nepal",
"NL" => "Netherlands",
"AN" => "Netherlands Antilles",
"NT" => "Neutral Zone",
"NC" => "New Caledonia",
"NZ" => "New Zealand",
"NI" => "Nicaragua",
"NE" => "Niger",
"NG" => "Nigeria",
"NU" => "Niue",
"NF" => "Norfolk Island",
"KP" => "North Korea",
"VD" => "North Vietnam",
"MP" => "Northern Mariana Islands",
"NO" => "Norway",
"OM" => "Oman",
"PC" => "Pacific Islands Trust Territory",
"PK" => "Pakistan",
"PW" => "Palau",
"PS" => "Palestinian Territories",
"PA" => "Panama",
"PZ" => "Panama Canal Zone",
"PG" => "Papua New Guinea",
"PY" => "Paraguay",
"YD" => "People's Democratic Republic of Yemen",
"PE" => "Peru",
"PH" => "Philippines",
"PN" => "Pitcairn Islands",
"PL" => "Poland",
"PT" => "Portugal",
"PR" => "Puerto Rico",
"QA" => "Qatar",
"RO" => "Romania",
"RU" => "Russia",
"RW" => "Rwanda",
"RE" => "Réunion",
"BL" => "Saint Barthélemy",
"SH" => "Saint Helena",
"KN" => "Saint Kitts and Nevis",
"LC" => "Saint Lucia",
"MF" => "Saint Martin",
"PM" => "Saint Pierre and Miquelon",
"VC" => "Saint Vincent and the Grenadines",
"WS" => "Samoa",
"SM" => "San Marino",
"SA" => "Saudi Arabia",
"SN" => "Senegal",
"RS" => "Serbia",
"CS" => "Serbia and Montenegro",
"SC" => "Seychelles",
"SL" => "Sierra Leone",
"SG" => "Singapore",
"SK" => "Slovakia",
"SI" => "Slovenia",
"SB" => "Solomon Islands",
"SO" => "Somalia",
"ZA" => "South Africa",
"GS" => "South Georgia and the South Sandwich Islands",
"KR" => "South Korea",
"ES" => "Spain",
"LK" => "Sri Lanka",
"SD" => "Sudan",
"SR" => "Suriname",
"SJ" => "Svalbard and Jan Mayen",
"SZ" => "Swaziland",
"SE" => "Sweden",
"CH" => "Switzerland",
"SY" => "Syria",
"ST" => "São Tomé and Príncipe",
"TW" => "Taiwan",
"TJ" => "Tajikistan",
"TZ" => "Tanzania",
"TH" => "Thailand",
"TL" => "Timor-Leste",
"TG" => "Togo",
"TK" => "Tokelau",
"TO" => "Tonga",
"TT" => "Trinidad and Tobago",
"TN" => "Tunisia",
"TR" => "Turkey",
"TM" => "Turkmenistan",
"TC" => "Turks and Caicos Islands",
"TV" => "Tuvalu",
"UM" => "U.S. Minor Outlying Islands",
"PU" => "U.S. Miscellaneous Pacific Islands",
"VI" => "U.S. Virgin Islands",
"UG" => "Uganda",
"UA" => "Ukraine",
"SU" => "Union of Soviet Socialist Republics",
"AE" => "United Arab Emirates",
"GB" => "United Kingdom",
"US" => "United States",
"ZZ" => "Unknown or Invalid Region",
"UY" => "Uruguay",
"UZ" => "Uzbekistan",
"VU" => "Vanuatu",
"VA" => "Vatican City",
"VE" => "Venezuela",
"VN" => "Vietnam",
"WK" => "Wake Island",
"WF" => "Wallis and Futuna",
"YE" => "Yemen",
"ZM" => "Zambia",
"ZW" => "Zimbabwe",
"AX" => "Åland Islands",
);


//// 

$countries = array(
"AF" => array('name'=>"Afghanistan", 'nativetongue'=>"‫افغانستان"),
"AX" => array('name'=>"Åland Islands", 'nativetongue'=>"Åland"),
"AL" => array('name'=>"Albania", 'nativetongue'=>"Shqipëri"),
"DZ" => array('name'=>"Algeria", 'nativetongue'=>"‫الجزائر"),
"AS" => array('name'=>"American Samoa", 'nativetongue'=>""),
"AD" => array('name'=>"Andorra", 'nativetongue'=>""),
"AO" => array('name'=>"Angola", 'nativetongue'=>""),
"AI" => array('name'=>"Anguilla", 'nativetongue'=>""),
"AQ" => array('name'=>"Antarctica", 'nativetongue'=>""),
"AG" => array('name'=>"Antigua and Barbuda", 'nativetongue'=>""),
"AR" => array('name'=>"Argentina", 'nativetongue'=>""),
"AM" => array('name'=>"Armenia", 'nativetongue'=>"Հայաստան"),
"AW" => array('name'=>"Aruba", 'nativetongue'=>""),
"AC" => array('name'=>"Ascension Island", 'nativetongue'=>""),
"AU" => array('name'=>"Australia", 'nativetongue'=>""),
"AT" => array('name'=>"Austria", 'nativetongue'=>"Österreich"),
"AZ" => array('name'=>"Azerbaijan", 'nativetongue'=>"Azərbaycan"),
"BS" => array('name'=>"Bahamas", 'nativetongue'=>""),
"BH" => array('name'=>"Bahrain", 'nativetongue'=>"‫البحرين"),
"BD" => array('name'=>"Bangladesh", 'nativetongue'=>"বাংলাদেশ"),
"BB" => array('name'=>"Barbados", 'nativetongue'=>""),
"BY" => array('name'=>"Belarus", 'nativetongue'=>"Беларусь"),
"BE" => array('name'=>"Belgium", 'nativetongue'=>"België"),
"BZ" => array('name'=>"Belize", 'nativetongue'=>""),
"BJ" => array('name'=>"Benin", 'nativetongue'=>"Bénin"),
"BM" => array('name'=>"Bermuda", 'nativetongue'=>""),
"BT" => array('name'=>"Bhutan", 'nativetongue'=>"འབྲུག"),
"BO" => array('name'=>"Bolivia", 'nativetongue'=>""),
"BA" => array('name'=>"Bosnia and Herzegovina", 'nativetongue'=>"Босна и Херцеговина"),
"BW" => array('name'=>"Botswana", 'nativetongue'=>""),
"BV" => array('name'=>"Bouvet Island", 'nativetongue'=>""),
"BR" => array('name'=>"Brazil", 'nativetongue'=>"Brasil"),
"IO" => array('name'=>"British Indian Ocean Territory",'nativetongue'=>""),
"VG" => array('name'=>"British Virgin Islands", 'nativetongue'=>""),
"BN" => array('name'=>"Brunei", 'nativetongue'=>""),
"BG" => array('name'=>"Bulgaria", 'nativetongue'=>"България"),
"BF" => array('name'=>"Burkina Faso", 'nativetongue'=>""),
"BI" => array('name'=>"Burundi", 'nativetongue'=>"Uburundi"),
"KH" => array('name'=>"Cambodia", 'nativetongue'=>"កម្ពុជា"),
"CM" => array('name'=>"Cameroon", 'nativetongue'=>"Cameroun"),
"CA" => array('name'=>"Canada", 'nativetongue'=>""),
"IC" => array('name'=>"Canary Islands", 'nativetongue'=>"islas Canarias"),
"CV" => array('name'=>"Cape Verde", 'nativetongue'=>"Kabu Verdi"),
"BQ" => array('name'=>"Caribbean Netherlands", 'nativetongue'=>""),
"KY" => array('name'=>"Cayman Islands", 'nativetongue'=>""),
"CF" => array('name'=>"Central African Republic",'nativetongue'=>"République centrafricaine"),
"EA" => array('name'=>"Ceuta and Melilla", 'nativetongue'=>"Ceuta y Melilla"),
"TD" => array('name'=>"Chad", 'nativetongue'=>"Tchad"),
"CL" => array('name'=>"Chile", 'nativetongue'=>""),
"CN" => array('name'=>"China", 'nativetongue'=>"中国"),
"CX" => array('name'=>"Christmas Island", 'nativetongue'=>""),
"CP" => array('name'=>"Clipperton Island", 'nativetongue'=>""),
"CC" => array('name'=>"Cocos (Keeling) Islands", 'nativetongue'=>"Kepulauan Cocos (Keeling)"),
"CO" => array('name'=>"Colombia", 'nativetongue'=>""),
"KM" => array('name'=>"Comoros", 'nativetongue'=>"‫جزر القمر"),
"CD" => array('name'=>"Congo (DRC)", 'nativetongue'=>"Jamhuri ya Kidemokrasia ya Kongo"),
"CG" => array('name'=>"Congo (Republic)", 'nativetongue'=>"Congo-Brazzaville"),
"CK" => array('name'=>"Cook Islands", 'nativetongue'=>""),
"CR" => array('name'=>"Costa Rica", 'nativetongue'=>""),
"CI" => array('name'=>"Côte d’Ivoire", 'nativetongue'=>""),
"HR" => array('name'=>"Croatia", 'nativetongue'=>"Hrvatska"),
"CU" => array('name'=>"Cuba", 'nativetongue'=>""),
"CW" => array('name'=>"Curaçao", 'nativetongue'=>""),
"CY" => array('name'=>"Cyprus", 'nativetongue'=>"Κύπρος"),
"CZ" => array('name'=>"Czech Republic", 'nativetongue'=>"Česká republika"),
"DK" => array('name'=>"Denmark", 'nativetongue'=>"Danmark"),
"DG" => array('name'=>"Diego Garcia", 'nativetongue'=>""),
"DJ" => array('name'=>"Djibouti", 'nativetongue'=>""),
"DM" => array('name'=>"Dominica", 'nativetongue'=>""),
"DO" => array('name'=>"Dominican Republic", 'nativetongue'=>"República Dominicana"),
"EC" => array('name'=>"Ecuador", 'nativetongue'=>""),
"EG" => array('name'=>"Egypt", 'nativetongue'=>"‫مصر"),
"SV" => array('name'=>"El Salvador", 'nativetongue'=>""),
"GQ" => array('name'=>"Equatorial Guinea",'nativetongue'=>"Guinea Ecuatorial"),
"ER" => array('name'=>"Eritrea", 'nativetongue'=>""),
"EE" => array('name'=>"Estonia", 'nativetongue'=>"Eesti"),
"ET" => array('name'=>"Ethiopia", 'nativetongue'=>""),
"FK" => array('name'=>"Falkland Islands", 'nativetongue'=>"Islas Malvinas"),
"FO" => array('name'=>"Faroe Islands", 'nativetongue'=>"Føroyar"),
"FJ" => array('name'=>"Fiji", 'nativetongue'=>""),
"FI" => array('name'=>"Finland", 'nativetongue'=>"Suomi"),
"FR" => array('name'=>"France", 'nativetongue'=>""),
"GF" => array('name'=>"French Guiana", 'nativetongue'=>"Guyane française"),
"PF" => array('name'=>"French Polynesia", 'nativetongue'=>"Polynésie française"),
"TF" => array('name'=>"French Southern Territories", 'nativetongue'=>"Terres australes françaises"),
"GA" => array('name'=>"Gabon", 'nativetongue'=>""),
"GM" => array('name'=>"Gambia", 'nativetongue'=>""),
"GE" => array('name'=>"Georgia", 'nativetongue'=>"საქართველო"),
"DE" => array('name'=>"Germany", 'nativetongue'=>"Deutschland"),
"GH" => array('name'=>"Ghana", 'nativetongue'=>"Gaana"),
"GI" => array('name'=>"Gibraltar", 'nativetongue'=>""),
"GR" => array('name'=>"Greece", 'nativetongue'=>"Ελλάδα"),
"GL" => array('name'=>"Greenland", 'nativetongue'=>"Kalaallit Nunaat"),
"GD" => array('name'=>"Grenada", 'nativetongue'=>""),
"GP" => array('name'=>"Guadeloupe", 'nativetongue'=>""),
"GU" => array('name'=>"Guam", 'nativetongue'=>""),
"GT" => array('name'=>"Guatemala", 'nativetongue'=>""),
"GG" => array('name'=>"Guernsey", 'nativetongue'=>""),
"GN" => array('name'=>"Guinea", 'nativetongue'=>"Guinée"),
"GW" => array('name'=>"Guinea-Bissau", 'nativetongue'=>"Guiné Bissau"),
"GY" => array('name'=>"Guyana", 'nativetongue'=>""),
"HT" => array('name'=>"Haiti", 'nativetongue'=>""),
"HM" => array('name'=>"Heard & McDonald Islands", 'nativetongue'=>""),
"HN" => array('name'=>"Honduras", 'nativetongue'=>""),
"HK" => array('name'=>"Hong Kong", 'nativetongue'=>"香港"),
"HU" => array('name'=>"Hungary", 'nativetongue'=>"Magyarország"),
"IS" => array('name'=>"Iceland", 'nativetongue'=>"Ísland"),
"IN" => array('name'=>"India", 'nativetongue'=>"भारत"),
"ID" => array('name'=>"Indonesia", 'nativetongue'=>""),
"IR" => array('name'=>"Iran", 'nativetongue'=>"‫ایران"),
"IQ" => array('name'=>"Iraq", 'nativetongue'=>"‫العراق"),
"IE" => array('name'=>"Ireland", 'nativetongue'=>""),
"IM" => array('name'=>"Isle of Man", 'nativetongue'=>""),
"IL" => array('name'=>"Israel", 'nativetongue'=>"‫ישראל"),
"IT" => array('name'=>"Italy", 'nativetongue'=>"Italia"),
"JM" => array('name'=>"Jamaica", 'nativetongue'=>""),
"JP" => array('name'=>"Japan", 'nativetongue'=>"日本"),
"JE" => array('name'=>"Jersey", 'nativetongue'=>""),
"JO" => array('name'=>"Jordan", 'nativetongue'=>"‫الأردن"),
"KZ" => array('name'=>"Kazakhstan", 'nativetongue'=>"Казахстан"),
"KE" => array('name'=>"Kenya", 'nativetongue'=>""),
"KI" => array('name'=>"Kiribati", 'nativetongue'=>""),
"XK" => array('name'=>"Kosovo", 'nativetongue'=>"Kosovë"),
"KW" => array('name'=>"Kuwait", 'nativetongue'=>"‫الكويت"),
"KG" => array('name'=>"Kyrgyzstan", 'nativetongue'=>"Кыргызстан"),
"LA" => array('name'=>"Laos", 'nativetongue'=>"ລາວ"),
"LV" => array('name'=>"Latvia", 'nativetongue'=>"Latvija"),
"LB" => array('name'=>"Lebanon", 'nativetongue'=>"‫لبنان"),
"LS" => array('name'=>"Lesotho", 'nativetongue'=>""),
"LR" => array('name'=>"Liberia", 'nativetongue'=>""),
"LY" => array('name'=>"Libya", 'nativetongue'=>"‫ليبيا"),
"LI" => array('name'=>"Liechtenstein", 'nativetongue'=>""),
"LT" => array('name'=>"Lithuania", 'nativetongue'=>"Lietuva"),
"LU" => array('name'=>"Luxembourg", 'nativetongue'=>""),
"MO" => array('name'=>"Macau", 'nativetongue'=>"澳門"),
"MK" => array('name'=>"Macedonia (FYROM)",'nativetongue'=>"Македонија"),
"MG" => array('name'=>"Madagascar", 'nativetongue'=>"Madagasikara"),
"MW" => array('name'=>"Malawi", 'nativetongue'=>""),
"MY" => array('name'=>"Malaysia", 'nativetongue'=>""),
"MV" => array('name'=>"Maldives", 'nativetongue'=>""),
"ML" => array('name'=>"Mali", 'nativetongue'=>""),
"MT" => array('name'=>"Malta", 'nativetongue'=>""),
"MH" => array('name'=>"Marshall Islands", 'nativetongue'=>""),
"MQ" => array('name'=>"Martinique", 'nativetongue'=>""),
"MR" => array('name'=>"Mauritania", 'nativetongue'=>"‫موريتانيا"),
"MU" => array('name'=>"Mauritius", 'nativetongue'=>"Moris"),
"YT" => array('name'=>"Mayotte", 'nativetongue'=>""),
"MX" => array('name'=>"Mexico", 'nativetongue'=>""),
"FM" => array('name'=>"Micronesia", 'nativetongue'=>""),
"MD" => array('name'=>"Moldova", 'nativetongue'=>"Republica Moldova"),
"MC" => array('name'=>"Monaco", 'nativetongue'=>""),
"MN" => array('name'=>"Mongolia", 'nativetongue'=>"Монгол"),
"ME" => array('name'=>"Montenegro", 'nativetongue'=>"Crna Gora"),
"MS" => array('name'=>"Montserrat", 'nativetongue'=>""),
"MA" => array('name'=>"Morocco", 'nativetongue'=>"‫المغرب"),
"MZ" => array('name'=>"Mozambique", 'nativetongue'=>"Moçambique"),
"MM" => array('name'=>"Myanmar (Burma)", 'nativetongue'=>"မြန်မာ"),
"NA" => array('name'=>"Namibia", 'nativetongue'=>"Namibië"),
"NR" => array('name'=>"Nauru", 'nativetongue'=>""),
"NP" => array('name'=>"Nepal", 'nativetongue'=>"नेपाल"),
"NL" => array('name'=>"Netherlands", 'nativetongue'=>"Nederland"),
"NC" => array('name'=>"New Caledonia", 'nativetongue'=>"Nouvelle-Calédonie"),
"NZ" => array('name'=>"New Zealand", 'nativetongue'=>""),
"NI" => array('name'=>"Nicaragua", 'nativetongue'=>""),
"NE" => array('name'=>"Niger", 'nativetongue'=>"Nijar"),
"NG" => array('name'=>"Nigeria", 'nativetongue'=>""),
"NU" => array('name'=>"Niue", 'nativetongue'=>""),
"NF" => array('name'=>"Norfolk Island", 'nativetongue'=>""),
"MP" => array('name'=>"Northern Mariana Islands", 'nativetongue'=>""),
"KP" => array('name'=>"North Korea", 'nativetongue'=>"조선 민주주의 인민 공화국"),
"NO" => array('name'=>"Norway", 'nativetongue'=>"Norge"),
"OM" => array('name'=>"Oman", 'nativetongue'=>"‫عُمان"),
"PK" => array('name'=>"Pakistan", 'nativetongue'=>"‫پاکستان"),
"PW" => array('name'=>"Palau", 'nativetongue'=>""),
"PS" => array('name'=>"Palestine", 'nativetongue'=>"‫فلسطين"),
"PA" => array('name'=>"Panama", 'nativetongue'=>""),
"PG" => array('name'=>"Papua New Guinea", 'nativetongue'=>""),
"PY" => array('name'=>"Paraguay", 'nativetongue'=>""),
"PE" => array('name'=>"Peru", 'nativetongue'=>"Perú"),
"PH" => array('name'=>"Philippines", 'nativetongue'=>""),
"PN" => array('name'=>"Pitcairn Islands", 'nativetongue'=>""),
"PL" => array('name'=>"Poland", 'nativetongue'=>"Polska"),
"PT" => array('name'=>"Portugal", 'nativetongue'=>""),
"PR" => array('name'=>"Puerto Rico", 'nativetongue'=>""),
"QA" => array('name'=>"Qatar", 'nativetongue'=>"‫قطر"),
"RE" => array('name'=>"Réunion", 'nativetongue'=>"La Réunion"),
"RO" => array('name'=>"Romania", 'nativetongue'=>"România"),
"RU" => array('name'=>"Russia", 'nativetongue'=>"Россия"),
"RW" => array('name'=>"Rwanda", 'nativetongue'=>""),
"BL" => array('name'=>"Saint Barthélemy", 'nativetongue'=>"Saint-Barthélemy"),
"SH" => array('name'=>"Saint Helena", 'nativetongue'=>""),
"KN" => array('name'=>"Saint Kitts and Nevis", 'nativetongue'=>""),
"LC" => array('name'=>"Saint Lucia", 'nativetongue'=>""),
"MF" => array('name'=>"Saint Martin", 'nativetongue'=>""),
"PM" => array('name'=>"Saint Pierre and Miquelon", 'nativetongue'=>"Saint-Pierre-et-Miquelon"),
"WS" => array('name'=>"Samoa", 'nativetongue'=>""),
"SM" => array('name'=>"San Marino", 'nativetongue'=>""),
"ST" => array('name'=>"São Tomé and Príncipe", 'nativetongue'=>"São Tomé e Príncipe"),
"SA" => array('name'=>"Saudi Arabia", 'nativetongue'=>"‫المملكة العربية السعودية"),
"SN" => array('name'=>"Senegal", 'nativetongue'=>"Sénégal"),
"RS" => array('name'=>"Serbia", 'nativetongue'=>"Србија"),
"SC" => array('name'=>"Seychelles", 'nativetongue'=>""),
"SL" => array('name'=>"Sierra Leone", 'nativetongue'=>""),
"SG" => array('name'=>"Singapore", 'nativetongue'=>""),
"SX" => array('name'=>"Sint Maarten", 'nativetongue'=>""),
"SK" => array('name'=>"Slovakia", 'nativetongue'=>"Slovensko"),
"SI" => array('name'=>"Slovenia", 'nativetongue'=>"Slovenija"),
"SB" => array('name'=>"Solomon Islands", 'nativetongue'=>""),
"SO" => array('name'=>"Somalia", 'nativetongue'=>"Soomaaliya"),
"ZA" => array('name'=>"South Africa", 'nativetongue'=>""),
"GS" => array('name'=>"South Georgia & South Sandwich Islands", 'nativetongue'=>""),
"KR" => array('name'=>"South Korea", 'nativetongue'=>"대한민국"),
"SS" => array('name'=>"South Sudan", 'nativetongue'=>"‫جنوب السودان"),
"ES" => array('name'=>"Spain", 'nativetongue'=>"España"),
"LK" => array('name'=>"Sri Lanka", 'nativetongue'=>"ශ්‍රී ලංකාව"),
"VC" => array('name'=>"St. Vincent & Grenadines", 'nativetongue'=>""),
"SD" => array('name'=>"Sudan", 'nativetongue'=>"‫السودان"),
"SR" => array('name'=>"Suriname", 'nativetongue'=>""),
"SJ" => array('name'=>"Svalbard and Jan Mayen", 'nativetongue'=>"Svalbard og Jan Mayen"),
"SZ" => array('name'=>"Swaziland", 'nativetongue'=>""),
"SE" => array('name'=>"Sweden", 'nativetongue'=>"Sverige"),
"CH" => array('name'=>"Switzerland", 'nativetongue'=>"Schweiz"),
"SY" => array('name'=>"Syria", 'nativetongue'=>"‫سوريا"),
"TW" => array('name'=>"Taiwan", 'nativetongue'=>"台灣"),
"TJ" => array('name'=>"Tajikistan", 'nativetongue'=>""),
"TZ" => array('name'=>"Tanzania", 'nativetongue'=>""),
"TH" => array('name'=>"Thailand", 'nativetongue'=>"ไทย"),
"TL" => array('name'=>"Timor-Leste", 'nativetongue'=>""),
"TG" => array('name'=>"Togo", 'nativetongue'=>""),
"TK" => array('name'=>"Tokelau", 'nativetongue'=>""),
"TO" => array('name'=>"Tonga", 'nativetongue'=>""),
"TT" => array('name'=>"Trinidad and Tobago", 'nativetongue'=>""),
"TA" => array('name'=>"Tristan da Cunha", 'nativetongue'=>""),
"TN" => array('name'=>"Tunisia", 'nativetongue'=>"‫تونس"),
"TR" => array('name'=>"Turkey", 'nativetongue'=>"Türkiye"),
"TM" => array('name'=>"Turkmenistan", 'nativetongue'=>""),
"TC" => array('name'=>"Turks and Caicos Islands", 'nativetongue'=>""),
"TV" => array('name'=>"Tuvalu", 'nativetongue'=>""),
"UM" => array('name'=>"U.S. Outlying Islands", 'nativetongue'=>""),
"VI" => array('name'=>"U.S. Virgin Islands", 'nativetongue'=>""),
"UG" => array('name'=>"Uganda", 'nativetongue'=>""),
"UA" => array('name'=>"Ukraine", 'nativetongue'=>"Україна"),
"AE" => array('name'=>"United Arab Emirates", 'nativetongue'=>"‫الإمارات العربية المتحدة"),
"GB" => array('name'=>"United Kingdom", 'nativetongue'=>""),
"US" => array('name'=>"United States", 'nativetongue'=>""),
"UY" => array('name'=>"Uruguay", 'nativetongue'=>""),
"UZ" => array('name'=>"Uzbekistan", 'nativetongue'=>"Oʻzbekiston"),
"VU" => array('name'=>"Vanuatu", 'nativetongue'=>""),
"VA" => array('name'=>"Vatican City", 'nativetongue'=>"Città del Vaticano"),
"VE" => array('name'=>"Venezuela", 'nativetongue'=>""),
"VN" => array('name'=>"Vietnam", 'nativetongue'=>"Việt Nam"),
"WF" => array('name'=>"Wallis and Futuna", 'nativetongue'=>""),
"YE" => array('name'=>"Yemen", 'nativetongue'=>"‫اليمن"),
"ZM" => array('name'=>"Zambia", 'nativetongue'=>""),
"ZW" => array('name'=>"Zimbabwe", 'nativetongue'=>"")
); 

//// 

 $Countries = [
                    [ 'code' => 'US', 'name' => 'United States'],
                    [ 'code' => 'CA', 'name' => 'Canada'],
                    [ 'code' => 'AU', 'name' => 'Australia'],
                    [ 'code' => 'FR', 'name' => 'France'],
                    [ 'code' => 'DE', 'name' => 'Germany'],
                    [ 'code' => 'IS', 'name' => 'Iceland'],
                    [ 'code' => 'IE', 'name' => 'Ireland'],
                    [ 'code' => 'IT', 'name' => 'Italy'],
                    [ 'code' => 'ES', 'name' => 'Spain'],
                    [ 'code' => 'SE', 'name' => 'Sweden'],
                    [ 'code' => 'AT', 'name' => 'Austria'],
                    [ 'code' => 'BE', 'name' => 'Belgium'],
                    [ 'code' => 'FI', 'name' => 'Finland'],
                    [ 'code' => 'CZ', 'name' => 'Czech Republic'],
                    [ 'code' => 'DK', 'name' => 'Denmark'],
                    [ 'code' => 'NO', 'name' => 'Norway'],
                    [ 'code' => 'GB', 'name' => 'United Kingdom'],
                    [ 'code' => 'CH', 'name' => 'Switzerland'],
                    [ 'code' => 'NZ', 'name' => 'New Zealand'],
                    [ 'code' => 'RU', 'name' => 'Russian Federation'],
                    [ 'code' => 'PT', 'name' => 'Portugal'],
                    [ 'code' => 'NL', 'name' => 'Netherlands'],
                    [ 'code' => 'IM', 'name' => 'Isle of Man'],
                    [ 'code' => 'AF', 'name' => 'Afghanistan'],
                    [ 'code' => 'AX', 'name' => 'Aland Islands '],
                    [ 'code' => 'AL', 'name' => 'Albania'],
                    [ 'code' => 'DZ', 'name' => 'Algeria'],
                    [ 'code' => 'AS', 'name' => 'American Samoa'],
                    [ 'code' => 'AD', 'name' => 'Andorra'],
                    [ 'code' => 'AO', 'name' => 'Angola'],
                    [ 'code' => 'AI', 'name' => 'Anguilla'],
                    [ 'code' => 'AQ', 'name' => 'Antarctica'],
                    [ 'code' => 'AG', 'name' => 'Antigua and Barbuda'],
                    [ 'code' => 'AR', 'name' => 'Argentina'],
                    [ 'code' => 'AM', 'name' => 'Armenia'],
                    [ 'code' => 'AW', 'name' => 'Aruba'],
                    [ 'code' => 'AZ', 'name' => 'Azerbaijan'],
                    [ 'code' => 'BS', 'name' => 'Bahamas'],
                    [ 'code' => 'BH', 'name' => 'Bahrain'],
                    [ 'code' => 'BD', 'name' => 'Bangladesh'],
                    [ 'code' => 'BB', 'name' => 'Barbados'],
                    [ 'code' => 'BY', 'name' => 'Belarus'],
                    [ 'code' => 'BZ', 'name' => 'Belize'],
                    [ 'code' => 'BJ', 'name' => 'Benin'],
                    [ 'code' => 'BM', 'name' => 'Bermuda'],
                    [ 'code' => 'BT', 'name' => 'Bhutan'],
                    [ 'code' => 'BO', 'name' => 'Bolivia, Plurinational State of'],
                    [ 'code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius and Saba'],
                    [ 'code' => 'BA', 'name' => 'Bosnia and Herzegovina'],
                    [ 'code' => 'BW', 'name' => 'Botswana'],
                    [ 'code' => 'BV', 'name' => 'Bouvet Island'],
                    [ 'code' => 'BR', 'name' => 'Brazil'],
                    [ 'code' => 'IO', 'name' => 'British Indian Ocean Territory'],
                    [ 'code' => 'BN', 'name' => 'Brunei Darussalam'],
                    [ 'code' => 'BG', 'name' => 'Bulgaria'],
                    [ 'code' => 'BF', 'name' => 'Burkina Faso'],
                    [ 'code' => 'BI', 'name' => 'Burundi'],
                    [ 'code' => 'KH', 'name' => 'Cambodia'],
                    [ 'code' => 'CM', 'name' => 'Cameroon'],
                    [ 'code' => 'CV', 'name' => 'Cape Verde'],
                    [ 'code' => 'KY', 'name' => 'Cayman Islands'],
                    [ 'code' => 'CF', 'name' => 'Central African Republic'],
                    [ 'code' => 'TD', 'name' => 'Chad'],
                    [ 'code' => 'CL', 'name' => 'Chile'],
                    [ 'code' => 'CN', 'name' => 'China'],
                    [ 'code' => 'CX', 'name' => 'Christmas Island'],
                    [ 'code' => 'CC', 'name' => 'Cocos (Keeling) Islands'],
                    [ 'code' => 'CO', 'name' => 'Colombia'],
                    [ 'code' => 'KM', 'name' => 'Comoros'],
                    [ 'code' => 'CG', 'name' => 'Congo'],
                    [ 'code' => 'CD', 'name' => 'Congo, the Democratic Republic of the'],
                    [ 'code' => 'CK', 'name' => 'Cook Islands'],
                    [ 'code' => 'CR', 'name' => 'Costa Rica'],
                    [ 'code' => 'CI', 'name' => 'Cote d\'Ivoire'],
                    [ 'code' => 'HR', 'name' => 'Croatia'],
                    [ 'code' => 'CU', 'name' => 'Cuba'],
                    [ 'code' => 'CW', 'name' => 'Curaçao'],
                    [ 'code' => 'CY', 'name' => 'Cyprus'],
                    [ 'code' => 'DJ', 'name' => 'Djibouti'],
                    [ 'code' => 'DM', 'name' => 'Dominica'],
                    [ 'code' => 'DO', 'name' => 'Dominican Republic'],
                    [ 'code' => 'EC', 'name' => 'Ecuador'],
                    [ 'code' => 'EG', 'name' => 'Egypt'],
                    [ 'code' => 'SV', 'name' => 'El Salvador'],
                    [ 'code' => 'GQ', 'name' => 'Equatorial Guinea'],
                    [ 'code' => 'ER', 'name' => 'Eritrea'],
                    [ 'code' => 'EE', 'name' => 'Estonia'],
                    [ 'code' => 'ET', 'name' => 'Ethiopia'],
                    [ 'code' => 'FK', 'name' => 'Falkland Islands (Malvinas)'],
                    [ 'code' => 'FO', 'name' => 'Faroe Islands'],
                    [ 'code' => 'FJ', 'name' => 'Fiji'],
                    [ 'code' => 'GF', 'name' => 'French Guiana'],
                    [ 'code' => 'PF', 'name' => 'French Polynesia'],
                    [ 'code' => 'TF', 'name' => 'French Southern Territories'],
                    [ 'code' => 'GA', 'name' => 'Gabon'],
                    [ 'code' => 'GM', 'name' => 'Gambia'],
                    [ 'code' => 'GE', 'name' => 'Georgia'],
                    [ 'code' => 'GH', 'name' => 'Ghana'],
                    [ 'code' => 'GI', 'name' => 'Gibraltar'],
                    [ 'code' => 'GR', 'name' => 'Greece'],
                    [ 'code' => 'GL', 'name' => 'Greenland'],
                    [ 'code' => 'GD', 'name' => 'Grenada'],
                    [ 'code' => 'GP', 'name' => 'Guadeloupe'],
                    [ 'code' => 'GU', 'name' => 'Guam'],
                    [ 'code' => 'GT', 'name' => 'Guatemala'],
                    [ 'code' => 'GG', 'name' => 'Guernsey'],
                    [ 'code' => 'GN', 'name' => 'Guinea'],
                    [ 'code' => 'GW', 'name' => 'Guinea-Bissau'],
                    [ 'code' => 'GY', 'name' => 'Guyana'],
                    [ 'code' => 'HT', 'name' => 'Haiti'],
                    [ 'code' => 'HM', 'name' => 'Heard Island and McDonald Islands'],
                    [ 'code' => 'VA', 'name' => 'Holy See (Vatican City State)'],
                    [ 'code' => 'HN', 'name' => 'Honduras'],
                    [ 'code' => 'HK', 'name' => 'Hong Kong'],
                    [ 'code' => 'HU', 'name' => 'Hungary'],
                    [ 'code' => 'IN', 'name' => 'India'],
                    [ 'code' => 'ID', 'name' => 'Indonesia'],
                    [ 'code' => 'IR', 'name' => 'Iran, Islamic Republic of'],
                    [ 'code' => 'IQ', 'name' => 'Iraq'],
                    [ 'code' => 'IL', 'name' => 'Israel'],
                    [ 'code' => 'JM', 'name' => 'Jamaica'],
                    [ 'code' => 'JP', 'name' => 'Japan'],
                    [ 'code' => 'JE', 'name' => 'Jersey'],
                    [ 'code' => 'JO', 'name' => 'Jordan'],
                    [ 'code' => 'KZ', 'name' => 'Kazakhstan'],
                    [ 'code' => 'KE', 'name' => 'Kenya'],
                    [ 'code' => 'KI', 'name' => 'Kiribati'],
                    [ 'code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of'],
                    [ 'code' => 'KR', 'name' => 'Korea, Republic of'],
                    [ 'code' => 'KW', 'name' => 'Kuwait'],
                    [ 'code' => 'KG', 'name' => 'Kyrgyzstan'],
                    [ 'code' => 'LA', 'name' => 'Lao People\'s Democratic Republic'],
                    [ 'code' => 'LV', 'name' => 'Latvia'],
                    [ 'code' => 'LB', 'name' => 'Lebanon'],
                    [ 'code' => 'LS', 'name' => 'Lesotho'],
                    [ 'code' => 'LR', 'name' => 'Liberia'],
                    [ 'code' => 'LY', 'name' => 'Libyan Arab Jamahiriya'],
                    [ 'code' => 'LI', 'name' => 'Liechtenstein'],
                    [ 'code' => 'LT', 'name' => 'Lithuania'],
                    [ 'code' => 'LU', 'name' => 'Luxembourg'],
                    [ 'code' => 'MO', 'name' => 'Macao'],
                    [ 'code' => 'MK', 'name' => 'Macedonia'],
                    [ 'code' => 'MG', 'name' => 'Madagascar'],
                    [ 'code' => 'MW', 'name' => 'Malawi'],
                    [ 'code' => 'MY', 'name' => 'Malaysia'],
                    [ 'code' => 'MV', 'name' => 'Maldives'],
                    [ 'code' => 'ML', 'name' => 'Mali'],
                    [ 'code' => 'MT', 'name' => 'Malta'],
                    [ 'code' => 'MH', 'name' => 'Marshall Islands'],
                    [ 'code' => 'MQ', 'name' => 'Martinique'],
                    [ 'code' => 'MR', 'name' => 'Mauritania'],
                    [ 'code' => 'MU', 'name' => 'Mauritius'],
                    [ 'code' => 'YT', 'name' => 'Mayotte'],
                    [ 'code' => 'MX', 'name' => 'Mexico'],
                    [ 'code' => 'FM', 'name' => 'Micronesia, Federated States of'],
                    [ 'code' => 'MD', 'name' => 'Moldova, Republic of'],
                    [ 'code' => 'MC', 'name' => 'Monaco'],
                    [ 'code' => 'MN', 'name' => 'Mongolia'],
                    [ 'code' => 'ME', 'name' => 'Montenegro'],
                    [ 'code' => 'MS', 'name' => 'Montserrat'],
                    [ 'code' => 'MA', 'name' => 'Morocco'],
                    [ 'code' => 'MZ', 'name' => 'Mozambique'],
                    [ 'code' => 'MM', 'name' => 'Myanmar'],
                    [ 'code' => 'NA', 'name' => 'Namibia'],
                    [ 'code' => 'NR', 'name' => 'Nauru'],
                    [ 'code' => 'NP', 'name' => 'Nepal'],
                    [ 'code' => 'NC', 'name' => 'New Caledonia'],
                    [ 'code' => 'NI', 'name' => 'Nicaragua'],
                    [ 'code' => 'NE', 'name' => 'Niger'],
                    [ 'code' => 'NG', 'name' => 'Nigeria'],
                    [ 'code' => 'NU', 'name' => 'Niue'],
                    [ 'code' => 'NF', 'name' => 'Norfolk Island'],
                    [ 'code' => 'MP', 'name' => 'Northern Mariana Islands'],
                    [ 'code' => 'OM', 'name' => 'Oman'],
                    [ 'code' => 'PK', 'name' => 'Pakistan'],
                    [ 'code' => 'PW', 'name' => 'Palau'],
                    [ 'code' => 'PS', 'name' => 'Palestinian Territory, Occupied'],
                    [ 'code' => 'PA', 'name' => 'Panama'],
                    [ 'code' => 'PG', 'name' => 'Papua New Guinea'],
                    [ 'code' => 'PY', 'name' => 'Paraguay'],
                    [ 'code' => 'PE', 'name' => 'Peru'],
                    [ 'code' => 'PH', 'name' => 'Philippines'],
                    [ 'code' => 'PN', 'name' => 'Pitcairn'],
                    [ 'code' => 'PL', 'name' => 'Poland'],
                    [ 'code' => 'PR', 'name' => 'Puerto Rico'],
                    [ 'code' => 'QA', 'name' => 'Qatar'],
                    [ 'code' => 'RE', 'name' => 'Reunion'],
                    [ 'code' => 'RO', 'name' => 'Romania'],
                    [ 'code' => 'RW', 'name' => 'Rwanda'],
                    [ 'code' => 'BL', 'name' => 'Saint Barthélemy'],
                    [ 'code' => 'SH', 'name' => 'Saint Helena'],
                    [ 'code' => 'KN', 'name' => 'Saint Kitts and Nevis'],
                    [ 'code' => 'LC', 'name' => 'Saint Lucia'],
                    [ 'code' => 'MF', 'name' => 'Saint Martin (French part)'],
                    [ 'code' => 'PM', 'name' => 'Saint Pierre and Miquelon'],
                    [ 'code' => 'VC', 'name' => 'Saint Vincent and the Grenadines'],
                    [ 'code' => 'WS', 'name' => 'Samoa'],
                    [ 'code' => 'SM', 'name' => 'San Marino'],
                    [ 'code' => 'ST', 'name' => 'Sao Tome and Principe'],
                    [ 'code' => 'SA', 'name' => 'Saudi Arabia'],
                    [ 'code' => 'SN', 'name' => 'Senegal'],
                    [ 'code' => 'RS', 'name' => 'Serbia'],
                    [ 'code' => 'SC', 'name' => 'Seychelles'],
                    [ 'code' => 'SL', 'name' => 'Sierra Leone'],
                    [ 'code' => 'SG', 'name' => 'Singapore'],
                    [ 'code' => 'SX', 'name' => 'Sint Maarten (Dutch part)'],
                    [ 'code' => 'SK', 'name' => 'Slovakia'],
                    [ 'code' => 'SI', 'name' => 'Slovenia'],
                    [ 'code' => 'SB', 'name' => 'Solomon Islands'],
                    [ 'code' => 'SO', 'name' => 'Somalia'],
                    [ 'code' => 'ZA', 'name' => 'South Africa'],
                    [ 'code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands'],
                    [ 'code' => 'LK', 'name' => 'Sri Lanka'],
                    [ 'code' => 'SD', 'name' => 'Sudan'],
                    [ 'code' => 'SR', 'name' => 'Suriname'],
                    [ 'code' => 'SJ', 'name' => 'Svalbard and Jan Mayen'],
                    [ 'code' => 'SZ', 'name' => 'Swaziland'],
                    [ 'code' => 'SY', 'name' => 'Syrian Arab Republic'],
                    [ 'code' => 'TW', 'name' => 'Taiwan, Province of China'],
                    [ 'code' => 'TJ', 'name' => 'Tajikistan'],
                    [ 'code' => 'TZ', 'name' => 'Tanzania, United Republic of'],
                    [ 'code' => 'TH', 'name' => 'Thailand'],
                    [ 'code' => 'TL', 'name' => 'Timor-Leste'],
                    [ 'code' => 'TG', 'name' => 'Togo'],
                    [ 'code' => 'TK', 'name' => 'Tokelau'],
                    [ 'code' => 'TO', 'name' => 'Tonga'],
                    [ 'code' => 'TT', 'name' => 'Trinidad and Tobago'],
                    [ 'code' => 'TN', 'name' => 'Tunisia'],
                    [ 'code' => 'TR', 'name' => 'Turkey'],
                    [ 'code' => 'TM', 'name' => 'Turkmenistan'],
                    [ 'code' => 'TC', 'name' => 'Turks and Caicos Islands'],
                    [ 'code' => 'TV', 'name' => 'Tuvalu'],
                    [ 'code' => 'UG', 'name' => 'Uganda'],
                    [ 'code' => 'UA', 'name' => 'Ukraine'],
                    [ 'code' => 'AE', 'name' => 'United Arab Emirates'],
                    [ 'code' => 'UM', 'name' => 'United States Minor Outlying Islands'],
                    [ 'code' => 'UY', 'name' => 'Uruguay'],
                    [ 'code' => 'UZ', 'name' => 'Uzbekistan'],
                    [ 'code' => 'VU', 'name' => 'Vanuatu'],
                    [ 'code' => 'VE', 'name' => 'Venezuela, Bolivarian Republic of'],
                    [ 'code' => 'VN', 'name' => 'Viet Nam'],
                    [ 'code' => 'VG', 'name' => 'Virgin Islands, British'],
                    [ 'code' => 'VI', 'name' => 'Virgin Islands, U.S.'],
                    [ 'code' => 'WF', 'name' => 'Wallis and Futuna'],
                    [ 'code' => 'YE', 'name' => 'Yemen'],
                    [ 'code' => 'ZM', 'name' => 'Zambia'],
                    [ 'code' => 'ZW', 'name' => 'Zimbabwe']
    ];

///


?>
